In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error

In [2]:
trainclean = pd.read_csv('trainclean.csv')

In [3]:
xtest = pd.read_csv('testclean.csv')

In [4]:
#trainclean['Overall Qual'] = trainclean['Overall Qual'].astype(str)

In [5]:
list(trainclean.select_dtypes(['object']).columns) #Columns to OHE

['MS Zoning',
 'Street',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Land Slope',
 'Neighborhood',
 'Condition 1',
 'Condition 2',
 'Bldg Type',
 'Roof Matl',
 'Exterior 1st',
 'Mas Vnr Type',
 'Exter Qual',
 'Foundation',
 'Bsmt Qual',
 'Heating QC',
 'Central Air',
 'Kitchen Qual',
 'Fireplace Qu',
 'Garage Type',
 'Garage Qual',
 'Paved Drive',
 'Fence']

Overall Qual,
Overall Cond,
MS SubClass,
    All are ints but serve as a scale rating 

In [6]:
xtest = xtest.drop(columns=['Id'])

In [7]:
X = trainclean.drop(columns=['SalePrice', 'Id'])

In [8]:
y = trainclean['SalePrice']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Modeling

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [11]:
le = LabelEncoder()

In [12]:
ohe = OneHotEncoder()

In [13]:
from sklearn.compose import make_column_transformer

In [14]:
ridge = Ridge()
lr = LinearRegression()
lasso = Lasso()
elast = ElasticNet()

In [15]:
column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), [
 'MS Zoning',
 'Street',
 'Lot Shape',
 'Land Contour',
 'Utilities',
 'Lot Config',
 'Land Slope',
 'Neighborhood',
 'Condition 1',
 'Condition 2',
 'Bldg Type',

 'Roof Matl',
 'Exterior 1st',
 'Mas Vnr Type',
 'Mas Vnr Area',
 'Exter Qual',
 'Foundation',
 'Bsmt Qual',



 'Heating QC',
 'Central Air',

 'Kitchen Qual',

 'Fireplace Qu',
 'Garage Type',

 'Garage Qual',
 'Paved Drive',
 'Fence']), remainder='passthrough')

## Baseline Score

In [16]:
#lr.fit(X,y)

In [17]:
#lr.score(X, y)

In [18]:
#cross_val_score(lr, X, y) Not sure how to do this, i cant seem to pass the column transformer in the lr.fit

## Pipeline

In [19]:
ridgepipe = make_pipeline(column_trans, StandardScaler(with_mean=False), Ridge())

In [20]:
#lassopipe = make_pipeline(column_trans, StandardScaler(with_mean=False), Lasso(max_iter = 100000))

In [21]:
lrpipe = make_pipeline(column_trans, StandardScaler(with_mean=False), LinearRegression())

In [22]:
elastpipe = make_pipeline(column_trans, StandardScaler(with_mean=False), ElasticNet(max_iter = 100000))

## Fit

In [23]:
ridgepipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['MS Zoning', 'Street',
                                                   'Lot Shape', 'Land Contour',
                                                   'Utilities', 'Lot Config',
                                                   'Land Slope', 'Neighborhood',
                                                   'Condition 1', 'Condition 2',
                                                   'Bldg Type', 'Roof Matl',
                                                   'Exterior 1st',
                                                   'Mas Vnr Type',
                                                   'Mas Vnr Area', 'Exter Qual',
                                                   'Foundat

In [24]:
#lassopipe.fit(X_train, y_train)

In [25]:
lrpipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['MS Zoning', 'Street',
                                                   'Lot Shape', 'Land Contour',
                                                   'Utilities', 'Lot Config',
                                                   'Land Slope', 'Neighborhood',
                                                   'Condition 1', 'Condition 2',
                                                   'Bldg Type', 'Roof Matl',
                                                   'Exterior 1st',
                                                   'Mas Vnr Type',
                                                   'Mas Vnr Area', 'Exter Qual',
                                                   'Foundat

elastpipe.fit(X_train, y_train)

## Pipe Score

In [26]:
ridgepipe.score(X_test, y_test)

0.8110844592358217

In [27]:
#lassopipe.score(X_test, y_test)

In [28]:
lrpipe.score(X_test, y_test)

0.8087304834469347

In [29]:
elastpipe.score(X_train, y_train)

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

## Cross Val Score

In [30]:
cross_val_score(lrpipe, X, y, cv=10)

array([0.85499898, 0.89322948, 0.89153405, 0.88909126, 0.62498931,
       0.9069344 , 0.87247399, 0.87433821, 0.87992154, 0.67106914])

In [31]:
cross_val_score(ridgepipe, X, y, cv=10)

array([0.85644341, 0.89588244, 0.88845388, 0.89153723, 0.63689108,
       0.90632683, 0.87332433, 0.87250046, 0.87926258, 0.6781732 ])

In [32]:
#cross_val_score(lassopipe, X, y, cv=10)

In [33]:
cross_val_score(elastpipe, X, y, cv=10)

array([0.84555251, 0.89799881, 0.88011133, 0.89063621, 0.73328057,
       0.87103827, 0.87703545, 0.85590785, 0.84621641, 0.73968419])

## Pipe Prediction error

#### Ridge pipe preds error

In [58]:
ridgepipepred = ridgepipe.predict(X_test)

In [59]:
mean_absolute_error(y_test, ridgepipepred)

18449.061134966905

In [60]:
mean_squared_error(y_test, ridgepipepred)

1122252915.3550315

In [62]:
mean_squared_error(y_test, ridgepipepred, squared=False)

33500.043512733406

#### Lasso pipe preds error

In [150]:
#lassopipepred = lassopipe.predict(X_test)

In [151]:
#mean_absolute_error(y_test, lassopipepred)

16195.917420534368

In [157]:
#mean_squared_error(y_test, lassopipepred)

583540673.4606578

In [162]:
#mean_squared_error(y_test, lassopipepred, squared=False)

24156.58654405994

#### Linear Regression pipe preds error

In [63]:
lrpipepred = lrpipe.predict(X_test)

In [64]:
mean_absolute_error(y_test, lrpipepred)

18419.15801469924

In [65]:
mean_squared_error(y_test, lrpipepred)

1123805177.645527

In [66]:
mean_squared_error(y_test, lrpipepred, squared=False)

33523.20357074375

#### Elastic Net pipe preds error

In [67]:
elastpipepred = elastpipe.predict(X_test)

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [68]:
mean_absolute_error(y_test, elastpipepred)

NameError: name 'elastpipepred' is not defined

In [69]:
mean_squared_error(y_test, elastpipepred)

NameError: name 'elastpipepred' is not defined

In [34]:
mean_squared_error(y_test, elastpipepred, squared=False)

NameError: name 'elastpipepred' is not defined

## Grid Search

In [70]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [71]:
ridge_alpha_list = [590, 595, 600, 605, 610]

In [124]:
elast_alpha_list = [.8, .9, 1, 1.1, 1.2]

## Grid Params

In [72]:
ridgeparams = {'ridge__alpha': ridge_alpha_list}

In [126]:
elastparams = {'elasticnet__alpha': elast_alpha_list}

## Making the Grid

In [73]:
ridgegrid = GridSearchCV(ridgepipe, ridgeparams)

In [128]:
elastgrid = GridSearchCV(elastpipe, elastparams)

## Fitting the Grid

In [129]:
elastgrid.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('onehotencoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['MS '
                                                                          'Zoning',
                                                                          'Street',
                                                                          'Lot '
                                                                          'Shape',
                                                                          'Land '
                                                                          'Contour',
                                                                          

In [74]:
ridgegrid.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('onehotencoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['MS '
                                                                          'Zoning',
                                                                          'Street',
                                                                          'Lot '
                                                                          'Shape',
                                                                          'Land '
                                                                          'Contour',
                                                                          

## Grid Score

In [131]:
elastgrid.score(X_test, y_test)

0.8937242976480366

In [75]:
ridgegrid.score(X_test, y_test)

0.8334828972197568

## Grid Cross Val Score

In [183]:
cross_val_score(elastgrid, X, y, cv=10)

array([0.8753019 , 0.91629792, 0.91651341, 0.9198362 , 0.71260051,
       0.89577353, 0.90822319, 0.88854739, 0.876621  , 0.74105708])

In [76]:
cross_val_score(ridgegrid, X, y, cv=10)

array([0.84927507, 0.90186539, 0.882244  , 0.89427092, 0.72009936,
       0.88187132, 0.87850884, 0.86227411, 0.85600339, 0.72937913])

## Best Grid Params

In [133]:
ridgegrid.best_params_

{'ridge__alpha': 600}

In [134]:
elastgrid.best_params_

{'elasticnet__alpha': 1}

## Grid Predict

#### Ridge prediction error

In [77]:
ridgepreds = ridgegrid.predict(X_test)

In [78]:
mean_absolute_error(y_test, ridgepreds)

19437.918017153614

In [79]:
mean_squared_error(y_test, ridgepreds)

1140866297.9818802

In [80]:
mean_squared_error(y_test, ridgepreds, squared=False)

33776.71236194962

#### Elastic Prediction Error

In [142]:
elastpreds = elastgrid.predict(X_test)

In [143]:
mean_absolute_error(y_test, elastpreds)

16358.84210174362

In [144]:
mean_squared_error(y_test, elastpreds)

666304661.3507104

In [145]:
mean_squared_error(y_test, elastpreds, squared=False)

25812.87782000896

## The production model should be ElasticNet